title: 'Macaulay's method"
author: Tom van Woudenberg from Delft University of Technology, built with <a href="https://teachbooks.tudelft.nl/">TeachBooks</a> and <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""></a> #Add your own name here
logo: figures/TUDelft_logo_rgb.png

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "figures/favicon.ico"
  baseurl :  "https://oit.tudelft.nl/Macaulays-method/" #Replace this with your own URL
  home_page_in_navbar       : false

sphinx:
  config:
    html_show_copyright: false
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: "https://github.com/TUDelft-books/Macaulays-method"
      path_to_docs: "book"
      repository_branch: "main"
      use_repository_button: true
      use_edit_page_button: true
      use_issues_button : true
      launch_buttons:
          thebe: true
    html_last_updated_fmt: '%B %-d, %Y'
    bibtex_default_style: myapastyle
    bibtex_reference_style: author_year_round
  local_extensions:
    apastyle: _ext/
    bracket_citation_style: _ext/
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - sphinx_tudelft_theme
    - sphinx_image_inverter

bibtex_bibfiles: 
  - references.bib
